"""
Serializers for Order model.

Serializers convert complex data types (like Django models) to Python data types
that can be easily rendered into JSON. They also handle validation and deserialization.
"""

from rest_framework import serializers
from .models import Order


class OrderSerializer(serializers.ModelSerializer):
    """
    Serializer for Order model.
    
    This converts Order model instances to/from JSON format.
    It handles all the fields automatically based on the model.
    """
    
    # Read-only fields (automatically generated, user doesn't provide these)
    username = serializers.CharField(source='user.username', read_only=True)
    
    class Meta:
        model = Order
        fields = [
            'id',           # Order ID (auto-generated)
            'username',     # Username (from related User model)
            'item_name',    # Name of item ordered
            'price',        # Price per unit
            'quantity',     # Quantity ordered
            'total',        # Total price (calculated automatically)
            'created_at',   # When order was created
            'updated_at',   # When order was last updated
        ]
        
        # Fields that are read-only (generated by system, not provided by user)
        read_only_fields = ['id', 'username', 'total', 'created_at', 'updated_at']
    
    def validate_quantity(self, value):
        """
        Ensure quantity is at least 1.
        Django REST Framework calls this automatically when validating data.
        """
        if value < 1:
            raise serializers.ValidationError("Quantity must be at least 1.")
        return value
    
    def validate_price(self, value):
        """
        Ensure price is positive.
        Django REST Framework calls this automatically when validating data.
        """
        if value <= 0:
            raise serializers.ValidationError("Price must be positive.")
        return value
